baseURL = "http://www.example.com"
title = "Emilinho Janez"
theme = "hugo-coder"
languageCode = "es"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
pagination.pagerSize  = 6
enableEmoji = true

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
author = "Emilio Juárez"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Emilio Juárez personal website"
keywords = "blog,developer,personal"
info = ["Incursionando en Ciberseguridad", "Free Software", "Ciclista", "AI (NLP, Machine Learning)"]
avatarURL = "images/me_fondo_azul.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# Taxonomías personalizadas
[taxonomies]
category = "categories"
tag = "tags"
series = "series"
difficulty = "difficulty"
section = "sections"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Emilio-J4n3z"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/emilinho"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://twitter.com/emilinhone/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/emilinho/"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 5
url = "https://medium.com/"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "https://myhugosite.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

# CONFIGURACIÓN MULTIIDIOMA

# Español (idioma principal)
[languages.es]
languageName = ":es:"
title = "Emilinho Janez"
weight = 1
contentDir = "content/es"

[languages.es.params]
author = "Emilio Juárez"
info = ["Incursionando en Ciberseguridad", "Software Libre", "Ciclista", "IA (PLN, Machine Learning)"]
description = "Sitio web personal de Emilio Juárez"
keywords = "blog,desarrollador,personal"

[[languages.es.menu.main]]
name = "Acerca de"
weight = 1
url = "/about/"

#[[languages.es.menu.main]]
#name = "Blog"
#weight = 2
#url = "/posts/"

[[languages.es.menu.main]]
name = "TechSec"
weight = 2
url = "/posts/techsec/"

[[languages.es.menu.main]]
name = "Rutas"
weight = 3
url = "/posts/rutas/"

[[languages.es.menu.main]]
name = "Tinta"
weight = 4
url = "/posts/tinta/"

[[languages.es.menu.main]]
name = "Worldview"
weight = 5
url = "/posts/worldview/"

[[languages.es.menu.main]]
name = "Proyectos"
weight = 6
url = "/projects/"

[[languages.es.menu.main]]
name = "Contacto"
weight = 7
url = "/contact/"

# Inglés
[languages.en]
languageName = ":uk:"
title = "Emilinho Janez"
weight = 2
contentDir = "content/en"

[languages.en.params]
author = "Emilio Juárez"
info = ["Exploring Cybersecurity", "Free Software", "Cyclist", "AI (NLP, Machine Learning)"]
description = "Emilio Juárez personal website"
keywords = "blog,developer,personal"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "/about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[languages.en.menu.main]]
name = "TechSec"
weight = 3
url = "/posts/techsec/"

[[languages.en.menu.main]]
name = "Routes"
weight = 4
url = "/posts/rutas/"

[[languages.en.menu.main]]
name = "Ink"
weight = 5
url = "/posts/tinta/"

[[languages.en.menu.main]]
name = "Worldview"
weight = 6
url = "/posts/worldview/"

[[languages.en.menu.main]]
name = "Projects"
weight = 7
url = "/projects/"

[[languages.en.menu.main]]
name = "Contact"
weight = 8
url = "/contact/"

# Portugués Brasileño
[languages.pt-br]
languageName = ":brazil:"
title = "Emilinho Janez"
weight = 3
contentDir = "content/pt-br"

[languages.pt-br.params]
author = "Emilio Juárez"
info = ["Incursionando em Cibersegurança", "Software Livre", "Ciclista", "IA (PLN, Machine Learning)"]
description = "Site pessoal do Emilio Juárez"
keywords = "blog,desenvolvedor,pessoal"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "/about/"

[[languages.pt-br.menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[languages.pt-br.menu.main]]
name = "TechSec"
weight = 3
url = "/posts/techsec/"

[[languages.pt-br.menu.main]]
name = "Rotas"
weight = 4
url = "/posts/rutas/"

[[languages.pt-br.menu.main]]
name = "Tinta"
weight = 5
url = "/posts/tinta/"

[[languages.pt-br.menu.main]]
name = "Worldview"
weight = 6
url = "/posts/worldview/"

[[languages.pt-br.menu.main]]
name = "Projetos"
weight = 7
url = "/projects/"

[[languages.pt-br.menu.main]]
name = "Contato"
weight = 8
url = "/contact/"
